name: n8n

on:
  push:
    branches:
      - main
    paths:
      - 'src/content/posts/**'

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
            git diff ${{github.event.before}}..${{github.event.after}} --name-status --diff-filter=AM -- 'src/content/posts/*' | while read status file; do
              curl -X POST https://n8n.lem0n.cc/webhook/16956957-43f0-4980-a238-b7c4a7960f71 -H 'Authorization: ${{secrets.AUTH_HEADER_VALUE}}' -d filename=$file -d action=$status
            done
